name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: templatedb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Run migrations and fixtures
      run: /usr/bin/pg_dump templatedb > templatedb_dump.sql
    - name: Upload template to S3
      run: |
        # sudo find / -name pg_dump
        ## TODO: set credentials to be able to upload to S3
        aws s3api put-object --bucket template_bucket --key templatedb_dump.sql --body ./templatedb_dump.sql
