name: CI

on: [push]

jobs:
  # https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.10-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - uses: actions/checkout@v1
    - name: Create dump
      run: |
        sudo apt-get install postgresql-client
        # TODO: run migrations and fixtures here
        pg_dump -Fc -v --host=localhost --username=postgres -f testdb.dump
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Upload dump to S3
      run: |
        # TODO: set credentials to be able to upload to S3
        aws s3api put-object --bucket dump_bucket --key testdb_dump.sql --body ./testdb.dump
