name: CI

on: [push]

jobs:
  # https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - uses: actions/checkout@v1
    - name: Setup database template
      run: |
        sudo apt-get install postgresql-client
        wait-on tcp:5432
        psql -l
        # TODO: run migrations and fixtures here
        pg_dump postgres > templatedb_dump.sql
      env:
        # use localhost for the host here because we are running the job on the VM.
        # If we were running the job on in a container this would be postgres
        PG_USER: postgres
        PG_HOST: localhost
        PG_DATABASE: postgres
        PG_PASSWORD: postgres
        PG_PORT: ${{ job.services.postgres.ports['5432'] }}
    - name: Upload template to S3
      run: |
        # TODO: set credentials to be able to upload to S3
        aws s3api put-object --bucket template_bucket --key templatedb_dump.sql --body ./templatedb_dump.sql
