name: CI

on: [push]

jobs:
  # https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - uses: actions/checkout@v1
    - name: Create dump
      run: |
        sudo apt-get install postgresql-client
        # psql -l # TODO: remove this, just a test to see if we connect to the db
        # TODO: run migrations and fixtures here
        # pg_dump postgres > testdb_dump.sql
        # pg_dump postgres --host=localhost --dbname=postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/backend > testdb_dump.sql
        # pg_dump -Fc backend > testdb.dump
        # pg_dump -Fc -v --host=localhost --username=postgres --dbname=backend -f testdb.dump
        pg_dump -Fc -v --host=localhost -f testdb.dump
      env:
        PG_HOST: localhost
        PG_USER: postgres
        # PG_PASSWORD: postgres
    - name: Upload dump to S3
      run: |
        # TODO: set credentials to be able to upload to S3
        aws s3api put-object --bucket dump_bucket --key testdb_dump.sql --body ./testdb_dump.sql
